from __future__ import annotations

import stat
import subprocess
from pathlib import Path

import pytest

from ai_agent_launcher._errors import LauncherError
from ai_agent_launcher._launchers import read_launcher
from ai_agent_launcher._migration import migrate_legacy_config, migrate_legacy_launcher
from ai_agent_launcher._models import AgentId


def _git_worktree(tmp_path: Path) -> Path:
    worktree = tmp_path / "worktree"
    worktree.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=worktree, check=True)
    (worktree / "README.md").write_text("test\n", encoding="utf-8")
    return worktree


def test_migrate_trusted_legacy_config_maps_known_values_and_reports_unknown(
    tmp_path: Path,
) -> None:
    source = tmp_path / "legacy-config.sh"
    source.write_text(
        "\n".join(
            (
                'CODEX_HOME="/tmp/codex-home"',
                'CODEX_LAUNCHER_ADD_DIRS=("/tmp/one" "/tmp/two")',
                'CODEX_LAUNCHER_MODEL="gpt-5"',
                'CODEX_LAUNCHER_REASONING_EFFORT="high"',
                'CODEX_LAUNCHER_SANDBOX="read-only"',
                "CODEX_LAUNCHER_USE_RTK=0",
                "UNRELATED_LEGACY_SETTING=value",
            )
        )
        + "\n",
        encoding="utf-8",
    )
    target = tmp_path / "config.toml"

    assert migrate_legacy_config(source, target, trusted=True, replace=False) == (
        "UNRELATED_LEGACY_SETTING",
    )
    assert target.read_text(encoding="utf-8") == (
        "[core]\n"
        'writable_dirs = ["/tmp/one", "/tmp/two"]\n'
        "\n"
        "[agents.codex]\n"
        'home = "/tmp/codex-home"\n'
        'model = "gpt-5"\n'
        'reasoning_effort = "high"\n'
        'sandbox = "read-only"\n'
        "use_rtk = false\n"
    )
    assert stat.S_IMODE(target.stat().st_mode) == 0o600


def test_migrate_config_requires_explicit_trust(tmp_path: Path) -> None:
    source = tmp_path / "legacy-config.sh"
    source.write_text("CODEX_LAUNCHER_ADD_DIRS=()\n", encoding="utf-8")

    with pytest.raises(LauncherError, match="--trust-legacy-shell-config"):
        migrate_legacy_config(source, tmp_path / "config.toml", trusted=False, replace=False)


def test_migrate_legacy_launcher_checks_marker_and_preserves_mode(tmp_path: Path) -> None:
    worktree = _git_worktree(tmp_path)
    preparation = tmp_path / "prepare"
    preparation.write_text("#!/bin/sh\n", encoding="utf-8")
    preparation.chmod(0o755)
    source = tmp_path / "legacy-launcher"
    marker = "# generated by legacy launcher"
    source.write_text(
        "\n".join(
            (
                "#!/bin/bash",
                marker,
                f"# codex-launcher-worktree_dir-hex: {str(worktree).encode().hex()}",
                "# codex-launcher-default_session_id-hex: 706172656e742d73657373696f6e",
                f"# codex-launcher-extra-add-dir-hex: {str(tmp_path).encode().hex()}",
            )
        )
        + "\n",
        encoding="utf-8",
    )
    source.chmod(0o750)
    target = tmp_path / "migrated-launcher"

    migrate_legacy_launcher(
        source,
        target,
        agent_id=AgentId("codex"),
        marker=marker,
        preparation_path=preparation,
        replace=False,
    )

    metadata = read_launcher(target)
    assert metadata.worktree_dir == worktree.resolve()
    assert metadata.session is not None
    assert metadata.session.value == "parent-session"
    assert metadata.local_writable_dirs == (tmp_path.resolve(),)
    assert stat.S_IMODE(target.stat().st_mode) == 0o750

    with pytest.raises(LauncherError, match="expected marker"):
        migrate_legacy_launcher(
            source,
            tmp_path / "bad-marker",
            agent_id=AgentId("codex"),
            marker="# another marker",
            preparation_path=preparation,
            replace=False,
        )
